# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2fdda72b3bd82ee5f71a1971cfe74d3e"
application_url = "https://jake-passing-drugs-elementary.trycloudflare.com"
embedded = true
name = "Dev-TT-Site-Comp-Generator"
handle = "dev-tt-site-comp-generator"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_files,write_themes,read_products"

[auth]
redirect_urls = [
  "https://jake-passing-drugs-elementary.trycloudflare.com/auth/callback",
  "https://jake-passing-drugs-elementary.trycloudflare.com/auth/shopify/callback",
  "https://jake-passing-drugs-elementary.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "itgeeks-test.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
