# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e50e0b8c44ce565622d1184c2afb878d"
application_url = "https://british-radar-wear-times.trycloudflare.com"
embedded = true
name = "testing-products-app"
handle = "testing-products-app"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_files,write_themes"

[auth]
redirect_urls = [
  "https://british-radar-wear-times.trycloudflare.com/auth/callback",
  "https://british-radar-wear-times.trycloudflare.com/auth/shopify/callback",
  "https://british-radar-wear-times.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "dev-themes-testing.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
