# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "55f0c79bf7b86dab2c01e023a568c787"
application_url = "https://lt-sample-ahead-qualify.trycloudflare.com"
embedded = true
name = "Site Comp Generator"
handle = "product-customization-18"

[build]
include_config_on_deploy = true
dev_store_url = "dev-themes-testing.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_files,write_themes"

[auth]
redirect_urls = [
  "https://lt-sample-ahead-qualify.trycloudflare.com/auth/callback",
  "https://lt-sample-ahead-qualify.trycloudflare.com/auth/shopify/callback",
  "https://lt-sample-ahead-qualify.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
