# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2fdda72b3bd82ee5f71a1971cfe74d3e"
<<<<<<< HEAD
application_url = "https://publications-airplane-jonathan-curtis.trycloudflare.com"
=======
application_url = "https://senior-architecture-standing-exceed.trycloudflare.com"
>>>>>>> 6b8af32fd1f2535692b032b52378c86283cf4435
embedded = true
name = "Dev-TT-Site-Comp-Generator"
handle = "dev-tt-site-comp-generator"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_files,write_themes"

[auth]
redirect_urls = [
<<<<<<< HEAD
  "https://publications-airplane-jonathan-curtis.trycloudflare.com/auth/callback",
  "https://publications-airplane-jonathan-curtis.trycloudflare.com/auth/shopify/callback",
  "https://publications-airplane-jonathan-curtis.trycloudflare.com/api/auth/callback"
=======
  "https://senior-architecture-standing-exceed.trycloudflare.com/auth/callback",
  "https://senior-architecture-standing-exceed.trycloudflare.com/auth/shopify/callback",
  "https://senior-architecture-standing-exceed.trycloudflare.com/api/auth/callback"
>>>>>>> 6b8af32fd1f2535692b032b52378c86283cf4435
]

[pos]
embedded = false

[build]
dev_store_url = "itgeeks-test.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
