# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2fdda72b3bd82ee5f71a1971cfe74d3e"
<<<<<<< HEAD:shopify.app.dev-tt-site-comp-generator.toml
application_url = "https://atlas-egypt-script-request.trycloudflare.com"
=======
application_url = "https://settle-finite-sought-geography.trycloudflare.com"
>>>>>>> 4b395ad8db50f1548b4a0b927895bcac61cdaba0:shopify.app.toml
embedded = true
name = "Dev-TT-Site-Comp-Generator"
handle = "dev-tt-site-comp-generator"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_files,write_themes,read_products"

[auth]
redirect_urls = [
<<<<<<< HEAD:shopify.app.dev-tt-site-comp-generator.toml
  "https://atlas-egypt-script-request.trycloudflare.com/auth/callback",
  "https://atlas-egypt-script-request.trycloudflare.com/auth/shopify/callback",
  "https://atlas-egypt-script-request.trycloudflare.com/api/auth/callback"
=======
  "https://settle-finite-sought-geography.trycloudflare.com/auth/callback",
  "https://settle-finite-sought-geography.trycloudflare.com/auth/shopify/callback",
  "https://settle-finite-sought-geography.trycloudflare.com/api/auth/callback"
>>>>>>> 4b395ad8db50f1548b4a0b927895bcac61cdaba0:shopify.app.toml
]

[pos]
embedded = false

[build]
dev_store_url = "itgeeks-test.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
